// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToHTML(arg1, arg2) {
  return window['go']['main']['App']['ExportToHTML'](arg1, arg2);
}

export function ExportToHTMLAs(arg1) {
  return window['go']['main']['App']['ExportToHTMLAs'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}
