// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportToHTML(arg1:string,arg2:string):Promise<void>;

export function ExportToHTMLAs(arg1:string):Promise<string>;

export function GetAppVersion():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenFile():Promise<main.OpenFileResult>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<void>;

export function SaveFileAs(arg1:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;
